services:
  dev:
    build:
      context: .
    image: program-sequence-anchor
    working_dir: /workspace
    volumes:
      - .:/workspace
      - cargo-registry:/opt/rust/cargo/registry
      - cargo-git:/opt/rust/cargo/git
      - node-modules:/workspace/node_modules
      - target:/workspace/target
      - solana-config:/root/.config/solana
    stdin_open: true
    tty: true

  localnet:
    build:
      context: .
    image: program-sequence-anchor
    working_dir: /workspace
    command: solana-test-validator --reset --ledger /workspace/.ledger --rpc-port 8899 --faucet-port 9900 --bind-address 0.0.0.0
    volumes:
      - target:/workspace/target
      - solana-config:/root/.config/solana
      - ledger:/workspace/.ledger
    ports:
      - "8899:8899"
      - "8900:8900"
      - "9900:9900"
    stdin_open: true
    tty: true

volumes:
  cargo-registry:
  cargo-git:
  node-modules:
  target:
  solana-config:
  ledger:
